### PR TITLE
Feature/foreach

### PR DESCRIPTION
**Pull request by Lexidor**

### CODE REVIEW

**Comment by Lexidor** [comment]
`Keyset\foreach_with_key` does not constrain `KeyedTraversable<Tk, Tv>`'s `Tk` to `arraykey`. I copied that from `Keyset\map_with_key`.

**Comment by Lexidor** [comment]
I am a rather var_dump reliant programmer, so this code snippet appears quite often in my code.
```HACK
//...
|> Vec\map($$, $doSomeTransformation)
|> Vec\filter($$, $val ==> {\var_dump($val); return true;});
|> Vec\unique(//...
```
I want to call a side-effecty function (var_dump) on each element at a certain step, but I don't want to affect the value. I often hacked a `for_each` together with "filter and return true" or "map and return $value". This function formalizes such behavior.

**Comment by fredemmott** [comment]
This has came up a few times; one goal of the HSL is to be much smaller than the PHP standard library, so we do not want extremely similar functions; in this case, we generally recommend either:
- using `foreach()` blocks
- using `map()` and either returning the input or ignoring it completely

For debugging pipelines, one approach is:

```
|> ($x ==> { \var_dump($x); return $x; })($$)
```

Or, to borrow a ruby idom:

```
function tap<T>(T $in, (function(T):void) $callback): T {
  $callback($in);
  return $in;
}


|> tap($$, $x ==> { var_dump($x); })
```

**Comment by azjezz** [comment]
I think `each` would be better naming.

---

I can see little advantage of having `Vec\each`, but nothing not sure if it should be included in HSL.

Instead of : 
```hack
|> Vec\map($$, $doSomeTransformation)
|> Vec\each($$, $var ==> dump($var));
|> Vec\unique( // use $$
```

You can do : 
```hack
|> Vec\map($$, $doSomeTransformation)
|> tuple($$, Vec\map($$, $var ==> dump($var)));
|> Vec\unique( // use $$[0] 
```

**Comment by fredemmott** [comment]
```
|> tuple($$, Vec\map($$, $var ==> dump($var)));
```

... that should be a typechecker error... filing a bug

**Comment by Lexidor** [comment]
Understood

**Comment by fredemmott** [comment]
@azjezz `|> tuple('a', 'b')` does not return the tuple, it treats it as a callable and invokes it; I don't think the typechecker is aware of this

**Comment by fredemmott** [comment]
Sorry, actually `|> tuple()` is fine - just not a common pattern

**Comment by azjezz** [comment]
@fredemmott , here's an example that works fine, without type errors.

```hack
function asis<T>(T $var): T { return $var; }

<<__EntryPoint>>
function main(): void {
  $users = vec[
    'foo',
    'bar',
    'baz',
  ];

  $bar = map($users, ($user) ==> $user[0])
    |> tuple($$, feach($users, ($user) ==> \var_dump($user)))
    |> asis($$[0]);

  \var_dump($bar);
}
```

```hack
function map<Tv, T>(
  vec<Tv> $bar,
  (function(Tv): T) $call
): vec<T> {
  $result = vec[];
  foreach($bar as $val) {
    $result[] = $call($val);
  }
  return $result;
}

function feach<Tv, T>(
  vec<Tv> $bar, (function(Tv): T) $call
): vec<Tv> {
  foreach($bar as $val) {
    $call($val);
  }
  return $bar;
}

```

**Pull request closed without merging**
