### PR TITLE
Remove hsl dependency and support autoloading with ext_watchman

### PR DESCRIPTION
**Pull request by lexidor**

### CODE REVIEW

**Comment by lexidor** [comment]
MacOS failure is a failed brew install of hhvm.

**Comment by lexidor** [comment]
Let's try again on MacOS.

**Comment by lexidor** [comment]
Let's try again on MacOS.

**Comment by lexidor** [comment]
MacOS hhvm install fails:
```
  You have 2 outdated formulae installed.
  You can upgrade them with brew upgrade
  or list them with brew outdated.
```

**Comment by Atry** [comment]
But why didn't the nightly CI fail?

**Comment by lexidor** [comment]
CI run

**Comment by lexidor** [comment]
RUNNING CI

**Comment by Atry** [comment]
LGTM. Thank you!

**Pull request merged**
